name: Feature request
description: Something ctxjev could do that it doesn't.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem it would solve
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What you have in mind
