import { build } from 'esbuild'
import { builtinModules } from 'node:module'
import { readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

// Claude Code installs this plugin by cloning its repo, never running an install step, so the
// hooks can't rely on node_modules resolution for cross-package imports (e.g. `ctxjev-core`,
// only linked here via the pnpm workspace). Bundle all four entry points so they carry their own
// dependencies and need nothing but Node itself: the two compaction hooks (preCompact.js,
// sessionStartCompact.js), status.js, run by the skills, and statusHook.js, which answers
// /ctxjev:status before it reaches the model (and loads status.js to do it, only then: it runs on
// every prompt, so it carries only the check).
const OUTPUT_FILES = ['preCompact.js', 'sessionStartCompact.js', 'status.js', 'statusHook.js']
const MAX_BUNDLE_BYTES = 200_000

const result = await build({
  entryPoints: ['src/preCompact.ts', 'src/sessionStartCompact.ts', 'src/status.ts', 'src/statusHook.ts'],
  bundle: true,
  platform: 'node',
  format: 'esm',
  outdir: 'dist',
  allowOverwrite: true,
  minify: true,
  metafile: true,
})

// dist/ is committed (unlike every other package's), so keep it to exactly what hooks.json runs.
for (const file of await readdir('dist')) {
  if (!OUTPUT_FILES.includes(file)) await rm(`dist/${file}`)
}

// Any import left in the output that isn't a Node builtin would fail with ERR_MODULE_NOT_FOUND on
// a fresh install (0.1.8's bug). esbuild's metafile lists real imports, so this can't be fooled by
// string contents in the minified code.
const isBuiltin = (path) => path.startsWith('node:') || builtinModules.includes(path)
for (const [outFile, output] of Object.entries(result.metafile.outputs)) {
  const unbundled = [...new Set(output.imports.filter((i) => i.external && !isBuiltin(i.path)).map((i) => i.path))]
  if (unbundled.length > 0) {
    throw new Error(`${outFile} still imports ${unbundled.join(', ')} — esbuild failed to bundle it`)
  }
  // Every hook run loads this, and it's committed. A tokenizer pulled in through a core import once
  // grew preCompact.js from 24KB to 2.8MB.
  if (output.bytes > MAX_BUNDLE_BYTES) {
    throw new Error(`${outFile} is ${output.bytes} bytes (limit ${MAX_BUNDLE_BYTES}) — check what a new ctxjev-core import pulled in`)
  }
}

// THIRD_PARTY_NOTICES, next to LICENSE at the plugin's root (a marketplace install copies this
// directory and nothing else): the license and copyright notice of every third-party package whose
// code the bundles above contain, read from esbuild's own list of inputs (the fourth audit's P1-7).
// ctxjev-core is this repository's own code, under LICENSE. A bundled package with no license file
// fails the build, so a new dependency can't ship without its notice.
const packageDirs = new Set()
for (const input of Object.keys(result.metafile.inputs)) {
  const at = input.lastIndexOf('node_modules/')
  if (at === -1) continue
  const rest = input.slice(at + 'node_modules/'.length).split('/')
  packageDirs.add(input.slice(0, at) + 'node_modules/' + rest.slice(0, rest[0].startsWith('@') ? 2 : 1).join('/'))
}
const notices = []
for (const dir of [...packageDirs].sort()) {
  const pkg = JSON.parse(await readFile(join(dir, 'package.json'), 'utf8'))
  const licenseFile = (await readdir(dir)).find((f) => /^(?:licen[cs]e|copying)(?:\.(?:md|txt))?$/i.test(f))
  if (!licenseFile) throw new Error(`${pkg.name} is bundled but has no license file in ${dir}; add its notice to THIRD_PARTY_NOTICES by hand`)
  notices.push({ name: pkg.name, version: pkg.version, license: pkg.license, text: (await readFile(join(dir, licenseFile), 'utf8')).trim() })
}
notices.sort((a, b) => a.name.localeCompare(b.name))
await writeFile(
  'THIRD_PARTY_NOTICES',
  [
    '# Third-party notices',
    '',
    'The bundles in dist/ contain code from the packages below, each under its own license, reproduced',
    'here in full. Generated by esbuild.build.mjs from what the build actually bundled; do not edit by hand.',
    'The rest of dist/ is ctxjev\'s own code (ctxjev-core and this plugin), under LICENSE.',
    '',
    ...notices.flatMap(({ name, version, license, text }) => [`## ${name}`, '', `Version ${version}, ${license} license.`, '', text, '']),
  ].join('\n'),
)
